apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodeapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/nodeapp@sha256:19c828ff704a32704be641604726b4d7e0139b09b8bc1de960a685d80d57ac38
        name: container-image
        resources: {}
status: {}
