apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-testapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/redhat-appstudio/user-workload:karthik-jk-python-testapp
        name: container-image
        resources: {}
status: {}
